- UniverseScoutPlugin.js
> feat(plugin): add initial universe scout plugin

- javascript/utils/utils.js
I was working on upgrade plugins and found that I needed to reuse these.
> feat: add some utils for upgrades

- content/artifacts/artifactory/plugin.js
Let's you input custom coordinates to sort Untaken artifacts. It defaults to your home coordinates.
> sort Untaken by location

- content/utilities/map-export/plugin.js
@jacobrosenthal draws an outline for your map selection.
@ichub the API turned out pretty cool!
> feat: add draw method that outlines the map selection

- content/productivity/distribute-silver/plugin.js
Also didn't remove the message div which I accidentally did in my previous commit.
> Added min level planet to distribute to.

- content/utilities/voyage-time/plugin.js
incorrect voyage times when hour or minute == 1
> voyage time plugin hour/minute conditions

- README.md
For submitters and reviewers.
Please add anything else youve been looking for.
Could be a contributing.md or in github, but this seems fine.
> contribution guidelines

- content/productivity/sitrep/index.md
- content/productivity/sitrep/plugin.js
Only needed to change the last line to 
export default Plugin;
> updated for v 0.6

- content/productivity/remote-explore/README.md
- content/productivity/remote-explore/index.md
- content/productivity/remote-explore/plugin.js
It is baked in, but it would be nice to have this so people can tweak to their liking.
I just pulled in the TS version and remove the types, but that version has a lot of fixes/improvements/formatting.
> feat: Update RemoteExplore for v6

- content/productivity/remote-snarker/index.md
- content/productivity/remote-snarker/plugin.js
> v6 remote snarking plugin

- content/productivity/distribute-silver/plugin.js
Added a check to prevent trying to withdraw from empty space rift
> Fixed withdraw silver

- content/productivity/quick-upgrade/index.md
- content/productivity/quick-upgrade/plugin.js
- content/productivity/upgradeable-planets/index.md
- content/productivity/upgradeable-planets/plugin.js
also adjusts javascript utils to properly call planetCanUpgrade
> upgrades quick-upgrade and upgradeable-planets

- content/utilities/map-export/plugin.js
copying from clipboard into notepad takes too long
> add download button

- archetypes/default/plugin.js
- content/artifacts/artifactory/plugin.js
- content/artifacts/find-legendary/plugin.js
- content/artifacts/highlight-artifacts/plugin.js
- content/casual/theme-changer/plugin.js
- content/productivity/quick-upgrade/plugin.js
- content/productivity/upgradeable-planets/plugin.js
- content/strategic/wage-war/plugin.js
This doesn't make the plugins compatible with 0.6, but the imports need to be fixed so the `df-plugin-dev-server` can be run against this project using a generic glob like: `content/**/*.js`
> chore: Update import/exports

- content/artifacts/artifacts-finder/plugin.js
1. Change the prospect interval to 5 minutes and find will happen in 10 seconds after prospect finish.
2. Add concurrency respect actions to 10(can change the MAX_PROSPECTING variable easily)
> Improve the artifacts finder plugin.

- content/utilities/player-list/plugin.js
when player clicks the title of planets、energy、energyCap、energyAvail、silver、score and rank,
player list can be sorted by it.
> improve player-list plugin's sort 

- content/productivity/remote-snarker/plugin.js
> round 3 stuff

- content/productivity/remote-explore/plugin.js
These are the changes I made in the client but applied to the non-TS version.
> feat(remote-explore): Add TowardsCenter pattern as option

- content/productivity/crawl-planets/plugin.js
Attempting to fix the crawler.
> fix(crawl-planets): Pass correct values into capture func

- content/productivity/crawl-planets/plugin.js
minimumEnergyAllowed should stay constant
> crawl-planets bugfix

- content/productivity/remote-explore/plugin.js
Discussed this on discord yesterday. Changing tile size can improve performance and make the explorer feel more responsive.
> feat(remote-explorer): add configurable chunk size

- content/artifacts/artifact-automove/plugin.js
* Avoid too much unconfirmed tx
* fix the bug : move artifact to itself
> Update Plugin: Aritifact Automove

- content/utilities/highlight-friends/index.md
- content/utilities/highlight-friends/plugin.js
update for dark forest round v0.6.5
> Highlight Friends v0.6.5

- content/casual/highlight-my-planets/plugin.js
* Fix typo
* Only draw circle around those planets visible in the viewport.
> Fix Typo and Draw circle only around planets visible in the viewport.

- content/productivity/remote-snarker/plugin.js
- Dramatically simplifies the remote Snarker plugin code.
- Works with built in snarking queue rather than importing its own.
- Works with the new https://github.com/Bind/df-snarker changes which will work for arbitrary dark forest rounds.
> feat: much simpler remote snarker

- content/artifacts/easy-highlight-artifacts/plugin.js
enable filter to show planet with zero junk
@jacobrosenthal @phated
> Update easy-highlight-artifacts plugin

- content/artifacts/easy-highlight-artifacts/index.md
- content/casual/highlight-my-planets/index.md
- content/productivity/highlight-buffs/index.md
- content/productivity/range-attack/index.md
- content/productivity/upgrade-manager/index.md
- content/utilities/custom-hotkeys/index.md
- content/utilities/favourite-areas/index.md
these were tested by @Bulmenisaurus and confirmed working with the latest version of the game, so I've just bumped their version numbers.
> chore: upgrade compatability versions of plugins that work with 0.6.5
